# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ajrjBQjWU4twoaleCgZQbjcJYKa7Ve2E
"""

# app.py - Streamlit interface for CO₂ prediction

import streamlit as st
import joblib
import numpy as np

# Load model
model = joblib.load("xgboost_dreumes_model.pkl")

st.set_page_config(page_title="CO₂ Predictor - Room 0.05 Dreumes")
st.title("🧠 CO₂ Prediction App")
st.markdown("This app predicts hourly CO₂ levels in the room `0.05 Dreumes` based on time and recent values.")

# Sidebar inputs
st.sidebar.header("Input Parameters")
hour = st.sidebar.slider("Hour of Day (0-23)", min_value=0, max_value=23, value=10)
dayofweek = st.sidebar.selectbox("Day of the Week", [
    (0, "Monday"), (1, "Tuesday"), (2, "Wednesday"),
    (3, "Thursday"), (4, "Friday"), (5, "Saturday"), (6, "Sunday")
], format_func=lambda x: x[1])[0]
is_weekend = int(dayofweek in [5, 6])

prev_co2_1h = st.sidebar.number_input("CO₂ 1 hour ago (ppm)", min_value=300.0, max_value=2000.0, value=500.0)
prev_co2_2h = st.sidebar.number_input("CO₂ 2 hours ago (ppm)", min_value=300.0, max_value=2000.0, value=480.0)
delta_co2_1h = prev_co2_1h - prev_co2_2h

# Prepare input for prediction
input_features = np.array([[hour, dayofweek, is_weekend, prev_co2_1h, prev_co2_2h, delta_co2_1h]])

# Predict
predicted_co2 = model.predict(input_features)[0]

# Output
st.subheader("📈 Predicted CO₂ Level")
st.metric("CO₂ (ppm)", f"{predicted_co2:.2f}")

st.markdown("---")
st.caption("Model: XGBoost with engineered time features")
